# Site settings
title: Bar Tack Consulting
email:
url: http://www.bartackconsulting.com
description: Product management experts specializing in early stage startups with experience in San Francisco and Berlin. 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fff'

# Footer settings
footer: Bar Tack Consulting LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)#
#social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: github
#    url: 

# Build settings
markdown: kramdown
permalink: pretty
